package com.longfor.longjian.common.consts;

import com.google.common.collect.Maps;

import java.util.Map;

/**
 * 操作描述模板
 *
 * @author zkm
 * @date 2018/12/26 17:44
 */
public class OperatedDescTplConst {

    public static final Map<String, String> OPERATED_DESC_MAP = Maps.newHashMap();

    public static final String OPERATED_USER_LOGIN = "OPERATED_USER_LOGIN";

    // API
    public static final String OPERATED_REPORT_CHECK_TASK = "OPERATED_REPORT_CHECK_TASK";
    public static final String OPERATED_REPORT_WORK_TASK = "OPERATED_REPORT_WORK_TASK";
    public static final String OPERATED_REPORT_REPOSSESSION = "OPERATED_REPORT_REPOSSESSION";

    // 集团功能
    public static final String OPERATED_TEAM_GROUP_CATEGORY_CREATE = "TEAM_GROUP_CATEGORY_CREATE";
    public static final String OPERATED_TEAM_GROUP_CATEGORY_UPDATE = "TEAM_GROUP_CATEGORY_UPDATE";
    public static final String OPERATED_TEAM_GROUP_CATEGORY_DELETE = "TEAM_GROUP_CATEGORY_DELETE";
    public static final String OPERATED_TEAM_GROUP_CATEGORY_SAVE_RELS = "TEAM_GROUP_CATEGORY_SAVE_RELS";
    public static final String OPERATED_TEAM_GROUP_CHECK_ITEM_CREATE = "TEAM_GROUP_CHECK_ITEM_CREATE";
    public static final String OPERATED_TEAM_GROUP_CHECK_ITEM_UPDATE = "TEAM_GROUP_CHECK_ITEM_UPDATE";
    public static final String OPERATED_TEAM_GROUP_CHECK_ITEM_DELETE = "TEAM_GROUP_CHECK_ITEM_DELETE";
    public static final String OPERATED_TEAM_GROUP_CHECK_ITEM_UPLOAD = "TEAM_GROUP_CHECK_ITEM_UPLOAD";
    public static final String OPERATED_TEAM_GROUP_CHECK_STANDARD_CREATE = "TEAM_GROUP_CHECK_STANDARD_CREATE";
    public static final String OPERATED_TEAM_GROUP_CHECK_STANDARD_UPDATE = "TEAM_GROUP_CHECK_STANDARD_UPDATE";
    public static final String OPERATED_TEAM_GROUP_CHECK_STANDARD_DELETE = "TEAM_GROUP_CHECK_STANDARD_DELETE";
    public static final String OPERATED_TEAM_GROUP_PERMISSION_GROUP_CREATE = "OPERATED_TEAM_GROUP_PERMISSION_GROUP_CREATE";
    public static final String OPERATED_TEAM_GROUP_PERMISSION_GROUP_DELETE = "OPERATED_TEAM_GROUP_PERMISSION_GROUP_DELETE";
    public static final String OPERATED_TEAM_GROUP_PERMISSION_GROUP_UPDATE = "OPERATED_TEAM_GROUP_PERMISSION_GROUP_UPDATE";
    public static final String OPERATED_TEAM_GROUP_USER_CREATE_NEW = "OPERATED_TEAM_GROUP_USER_CREATE_NEW";
    public static final String OPERATED_TEAM_GROUP_USER_ADD = "OPERATED_TEAM_GROUP_USER_ADD";
    public static final String OPERATED_TEAM_GROUP_USER_UPDATE = "OPERATED_TEAM_GROUP_USER_UPDATE";
    public static final String OPERATED_TEAM_GROUP_USER_UPDATE_PASS = "OPERATED_TEAM_GROUP_USER_UPDATE_PASS";
    public static final String OPERATED_TEAM_GROUP_USER_DELETE = "OPERATED_TEAM_GROUP_USER_DELETE";
    public static final String OPERATED_TEAM_GROUP_USER_JOIN_PROJ = "OPERATED_TEAM_GROUP_USER_JOIN_PROJ";
    public static final String OPERATED_TEAM_GROUP_USER_REMOVE_PROJ = "OPERATED_TEAM_GROUP_USER_REMOVE_PROJ";
    public static final String OPERATED_TEAM_GROUP_USER_UPDATE_PROJ = "OPERATED_TEAM_GROUP_USER_UPDATE_PROJ";
    public static final String OPERATED_TEAM_GROUP_CREATE_TEAM = "OPERATED_TEAM_GROUP_CREATE_TEAM";
    public static final String OPERATED_TEAM_GROUP_UPDATE_TEAM = "OPERATED_TEAM_GROUP_UPDATE_TEAM";
    public static final String OPERATED_TEAM_GROUP_DELETE_TEAM = "OPERATED_TEAM_GROUP_DELETE_TEAM";
    public static final String OPERATED_TEAM_GROUP_SET_TEAM = "OPERATED_TEAM_GROUP_SET_TEAM";

    // 公司功能
    public static final String OPERATED_TEAM_CHECK_TASK_ISSUE_CANCEL = "OPERATED_TEAM_CHECK_TASK_ISSUE_CANCEL";
    public static final String OPERATED_TEAM_CHECK_TASK_ISSUE_APPROVE = "OPERATED_TEAM_CHECK_TASK_ISSUE_APPROVE";
    public static final String OPERATED_TEAM_CHECK_TASK_ISSUE_DELETE = "OPERATED_TEAM_CHECK_TASK_ISSUE_DELETE";
    public static final String OPERATED_TEAM_CREATE_PROJ = "OPERATED_TEAM_CREATE_PROJ";
    public static final String OPERATED_TEAM_CATEGORY_CREATE = "TEAM_CATEGORY_CREATE";
    public static final String OPERATED_TEAM_CATEGORY_UPDATE = "TEAM_CATEGORY_UPDATE";
    public static final String OPERATED_TEAM_CATEGORY_DELETE = "TEAM_CATEGORY_DELETE";
    public static final String OPERATED_TEAM_CATEGORY_SAVE_RELS = "TEAM_CATEGORY_SAVE_RELS";
    public static final String OPERATED_TEAM_CHECK_ITEM_CREATE = "TEAM_CHECK_ITEM_CREATE";
    public static final String OPERATED_TEAM_CHECK_ITEM_UPDATE = "TEAM_CHECK_ITEM_UPDATE";
    public static final String OPERATED_TEAM_CHECK_ITEM_DELETE = "TEAM_CHECK_ITEM_DELETE";
    public static final String OPERATED_TEAM_CHECK_ITEM_UPLOAD = "TEAM_CHECK_ITEM_UPLOAD";
    public static final String OPERATED_TEAM_CHECK_STANDARD_CREATE = "TEAM_CHECK_STANDARD_CREATE";
    public static final String OPERATED_TEAM_CHECK_STANDARD_UPDATE = "TEAM_CHECK_STANDARD_UPDATE";
    public static final String OPERATED_TEAM_CHECK_STANDARD_DELETE = "TEAM_CHECK_STANDARD_DELETE";
    public static final String OPERATED_TEAM_PROJ_CREATE = "OPERATED_TEAM_PROJ_CREATE";
    public static final String OPERATED_TEAM_PROJ_UPDATE = "OPERATED_TEAM_PROJ_UPDATE";
    public static final String OPERATED_TEAM_PROJ_DELETE = "OPERATED_TEAM_PROJ_DELETE";
    public static final String OPERATED_TEAM_CHECK_TASK_CREATE = "OPERATED_TEAM_CHECK_TASK_CREATE";
    public static final String OPERATED_TEAM_USER_CREATE_NEW = "OPERATED_TEAM_USER_CREATE_NEW";
    public static final String OPERATED_TEAM_USER_ADD = "OPERATED_TEAM_USER_ADD";
    public static final String OPERATED_TEAM_USER_UPDATE = "OPERATED_TEAM_USER_UPDATE";
    public static final String OPERATED_TEAM_USER_UPDATE_PASS = "OPERATED_TEAM_USER_ADD_PASS";
    public static final String OPERATED_TEAM_USER_DELETE = "OPERATED_TEAM_USER_DELETE";
    public static final String OPERATED_TEAM_USER_JOIN_PROJ = "OPERATED_TEAM_USER_JOIN_PROJ";
    public static final String OPERATED_TEAM_USER_REMOVE_PROJ = "OPERATED_TEAM_USER_REMOVE_PROJ";
    public static final String OPERATED_TEAM_USER_UPDATE_PROJ = "OPERATED_TEAM_USER_UPDATE_PROJ";
    public static final String OPERATED_TEAM_PERMISSION_GROUP_CREATE = "OPERATED_TEAM_PERMISSION_GROUP_CREATE";
    public static final String OPERATED_TEAM_PERMISSION_GROUP_DELETE = "OPERATED_TEAM_PERMISSION_GROUP_DELETE";
    public static final String OPERATED_TEAM_PERMISSION_GROUP_UPDATE = "OPERATED_TEAM_PERMISSION_GROUP_UPDATE";

    // 项目功能
    public static final String OPERATED_PROJ_WORK_TASK_CREATE = "PROJ_WORK_TASK_CREATE";
    public static final String OPERATED_PROJ_CREATE_CHECK_TASK = "OPERATED_PROJ_CREATE_CHECK_TASK";
    public static final String OPERATED_PROJ_UPDATE_CHECK_TASK = "OPERATED_PROJ_UPDATE_CHECK_TASK";
    public static final String OPERATED_PROJ_DELETE_CHECK_TASK = "OPERATED_PROJ_DELETE_CHECK_TASK";
    public static final String OPERATED_PROJ_AREA_CREATE = "OPERATED_PROJ_AREA_CREATE";
    public static final String OPERATED_PROJ_AREA_UPDATE = "OPERATED_PROJ_AREA_UPDATE";
    public static final String OPERATED_PROJ_AREA_DELETE = "OPERATED_PROJ_AREA_DELETE";
    public static final String OPERATED_PROJ_AREA_COPY = "OPERATED_PROJ_AREA_COPY";
    public static final String OPERATED_PROJ_AREA_CLASS_CREATE = "OPERATED_PROJ_AREA_CLASS_CREATE";
    public static final String OPERATED_PROJ_AREA_CLASS_UPDATE = "OPERATED_PROJ_AREA_CLASS_UPDATE";
    public static final String OPERATED_PROJ_AREA_CLASS_DELETE = "OPERATED_PROJ_AREA_CLASS_DELETE";
    public static final String OPERATED_PROJ_AREA_CLASS_COPY = "OPERATED_PROJ_AREA_CLASS_COPY";
    public static final String OPERATED_PROJ_SET_AREA_CLASS = "OPERATED_PROJ_SET_AREA_CLASS";
    public static final String OPERATED_PROJ_AREA_CLASS_CREATE_CHILDREN = "OPERATED_PROJ_AREA_CLASS_CREATE_CHILDREN";
    public static final String OPERATED_PROJ_AREA_CLASS_UPDATE_CHILDREN = "OPERATED_PROJ_AREA_CLASS_UPDATE_CHILDREN";
    public static final String OPERATED_PROJ_AREA_CLASS_DELETE_CHILDREN = "OPERATED_PROJ_AREA_CLASS_DELETE_CHILDREN";
    public static final String OPERATED_PROJ_CHECK_TASK_ISSUE_ASSIGN = "OPERATED_PROJ_CHECK_TASK_ISSUE_ASSIGN";
    public static final String OPERATED_PROJ_CHECK_TASK_ISSUE_CANCEL = "OPERATED_PROJ_CHECK_TASK_ISSUE_CANCEL";
    public static final String OPERATED_PROJ_CHECK_TASK_ISSUE_APPROVE = "OPERATED_PROJ_CHECK_TASK_ISSUE_APPROVE";
    public static final String OPERATED_PROJ_CHECK_TASK_ISSUE_DELETE = "OPERATED_PROJ_CHECK_TASK_ISSUE_DELETE";
    public static final String OPERATED_PROJ_UPDATE_SETTING = "OPERATED_PROJ_UPDATE_SETTING";

    static {
        OPERATED_DESC_MAP.put(OPERATED_USER_LOGIN, "用户登录:userId[%d]");

        // API
        OPERATED_DESC_MAP.put(OPERATED_REPORT_CHECK_TASK, "api上报检查任务:data[%s]");
        OPERATED_DESC_MAP.put(OPERATED_REPORT_WORK_TASK, "api上报施工任务:data[%s]");
        OPERATED_DESC_MAP.put(OPERATED_REPORT_REPOSSESSION, "api上报验房报告:data[%s]");

        // 公司功能
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CATEGORY_CREATE, "创建任务类型【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CATEGORY_UPDATE, "更新任务类型为【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CATEGORY_DELETE, "删除任务类型【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CATEGORY_SAVE_RELS, "保存任务类型【%s】的检查项关联");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_ITEM_CREATE, "创建检查项【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_ITEM_UPDATE, "更新检查项为【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_ITEM_DELETE, "删除检查项【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_ITEM_UPLOAD, "导入检查项和检查标准至【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_STANDARD_CREATE, "创建检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_STANDARD_UPDATE, "更新检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CHECK_STANDARD_DELETE, "删除检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_PERMISSION_GROUP_CREATE, "创建集团角色:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_PERMISSION_GROUP_DELETE, "删除集团角色: id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_PERMISSION_GROUP_UPDATE, "编辑集团角色: id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_CREATE_NEW, "集团新增人员: username[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_ADD, "集团添加人员: username[%s] teamId[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_UPDATE, "集团编辑人员:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_UPDATE_PASS, "集团修改人员密码:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_DELETE, "集团删除人员:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_JOIN_PROJ, "集团添加人员进项目: userId[%d] projId[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_REMOVE_PROJ, "集团把人员移除项目: userId[%d] projId[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_USER_UPDATE_PROJ, "集团里面修改项目人员角色: userId[%d] projId[%d] roleId[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_CREATE_TEAM, "集团创建公司: teamName[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_UPDATE_TEAM, "集团编辑公司: id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_DELETE_TEAM, "集团删除公司: id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_GROUP_SET_TEAM, "集团设置公司:id[%d]");

        // 公司功能
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_TASK_ISSUE_CANCEL, "（公司/集团）取消问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_TASK_ISSUE_APPROVE, "（公司/集团）销项问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_TASK_ISSUE_DELETE, "（公司/集团）删除问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CREATE_PROJ, "创建项目:[%s] Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CATEGORY_CREATE, "创建任务类型【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CATEGORY_UPDATE, "更新任务类型为【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CATEGORY_DELETE, "删除任务类型【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CATEGORY_SAVE_RELS, "保存任务类型【%s】的检查项关联");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_ITEM_CREATE, "创建检查项【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_ITEM_UPDATE, "更新检查项为【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_ITEM_DELETE, "删除检查项【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_ITEM_UPLOAD, "导入检查项和检查标准至【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_STANDARD_CREATE, "创建检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_STANDARD_UPDATE, "更新检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_STANDARD_DELETE, "删除检查标准【%s】");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PERMISSION_GROUP_CREATE, "创建公司角色:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PERMISSION_GROUP_DELETE, "删除公司角色:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PERMISSION_GROUP_UPDATE, "编辑公司角色:Id[%d] name:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PROJ_CREATE, "创建项目:[%s], Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PROJ_UPDATE, "编辑项目信息:Id[%d] name[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_PROJ_DELETE, "删除项目:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_CHECK_TASK_CREATE, "创建公司任务:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_CREATE_NEW, "新加人员:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_ADD, "添加人员: userName[%s]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_UPDATE, "编辑人员信息:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_UPDATE_PASS, "修改人员密码:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_DELETE, "删除人员:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_JOIN_PROJ, "添加人员进项目:userId[%d] projId:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_REMOVE_PROJ, "从项目里移除人员: userId[%d] projId:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_TEAM_USER_UPDATE_PROJ, "编辑人在项目的角色: userId[%d] roleId:[%d]");

        // 项目功能
        OPERATED_DESC_MAP.put(OPERATED_PROJ_WORK_TASK_CREATE, "创建了施工任务:[%d] 名字:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_CREATE_CHECK_TASK, "创建项目检查任务:[%s] Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_DELETE_CHECK_TASK, "删除项目检查任务:Id[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_UPDATE_CHECK_TASK, "编辑项目检查任务:Id[%d]");

        // 区域部分
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CREATE, "创建区域:[%s] Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_UPDATE, "更新区域:[%d] 操作:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_DELETE, "删除区域:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_COPY, "复制区域:[%s] 源Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_CREATE, "创建户型:[%s] Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_UPDATE, "更新户型:[%d] 操作:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_DELETE, "删除户型:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_COPY, "复制户型:[%s] 源Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_SET_AREA_CLASS, "分配户型:[%s] 户型Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_CREATE_CHILDREN, "新增户型子区域:[%s] 户型Id:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_UPDATE_CHILDREN, "更新户型子区域:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_AREA_CLASS_DELETE_CHILDREN, "删除户型子区域:[%d]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_CHECK_TASK_ISSUE_ASSIGN, "指派问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_CHECK_TASK_ISSUE_CANCEL, "取消问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_CHECK_TASK_ISSUE_APPROVE, "销项问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_CHECK_TASK_ISSUE_DELETE, "删除问题:[%s]");
        OPERATED_DESC_MAP.put(OPERATED_PROJ_UPDATE_SETTING, "更改项目配置: id[%d] key[%s] value[%s]");
    }
    
    public static final String getValue(String operatedDescTplConstKey) {
    	return OPERATED_DESC_MAP.get(operatedDescTplConstKey);
    }

}
